name: API tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start flask
        run: |
          export FLASK_APP=app/api.py
          export FLASK_ENV=development
          export PYTHONPATH=$GITHUB_WORKSPACE
          flask run &

      - name: Execute API tests
        run: |
          python3 -m pytest app/tests/api
